### ISSUE TITLE
Nothing to repeat

### ISSUE THREAD

**Issue by akroii** [feedbackmedia/contao-cearch-pro#4]
```
[13-Jul-2015 21:33:23 Europe/Berlin] 
PHP Warning: preg_match(): Compilation failed: nothing to repeat at offset 2 in /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/zCearchPro/classes/Search.php on line 696
#0 [internal function]: __error(2, 'preg_match(): C...', '/homepages/27/d...', 696, Array)
#1 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/zCearchPro/classes/Search.php(696): preg_match('/\\b++\\b/i', 'a, able, about,...')
#2 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/zCearchPro/classes/Search.php(287): Contao\Search::getExclude('++')
#3 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/core/classes/FrontendTemplate.php(298): Contao\Search::indexPage(Array)
#4 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/core/classes/FrontendTemplate.php(113): Contao\FrontendTemplate->addToSearchIndex()
#5 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/core/pages/PageRegular.php(186): Contao\FrontendTemplate->output(true)
#6 /homepages/27/d469023837/htdocs/contao-3.4.4/system/modules/core/controllers/FrontendIndex.php(244): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#7 /homepages/27/d469023837/htdocs/contao-3.4.4/index.php(20): Contao\FrontendIndex->run()
#8 {main}
 ```

Ich habe contao 3.4.4 mit Cearch 1.0.1

**Comment by bytehead** [comment]
Cearch 1.0.1 existiert gar nicht mehr: https://github.com/feedbackmedia/contao-cearch-pro/releases

PS: @smohring Release- und Commit-History nicht löschen/überschreiben.

**Comment by smohring** [comment]
Bitte nochmals mit der Search.php des neusten commits testen, sollte funktionieren:

https://github.com/feedbackmedia/contao-cearch-pro/blob/master/classes/Search.php
